ASSUMPTION_OUTDATED = "Assumption outdated"
BUTTON_SHOULD_BE_DISABLED = "Button should be disabled"
BUTTON_SHOULD_BE_ENABLED = "Button should be enabled"
CHANGE_NOT_SAVED = "Change is not saved"
CHANGE_WRONGLY_SAVED = "Change should not be saved"
CONTENT_MISMATCH = "Content mismatch"
UI_NOT_UPDATED = "UI is not updated"
UI_WRONGLY_UPDATED = "UI should not be updated"
